services:
    hand:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/local/hand
        ports:
            - '5260:5260'
            - '7053:7053'
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            MongoDb__Host: mongodb
            MongoDb__Port: 27017
            MongoDb__Username: ${MONGODB_USERNAME}
            MongoDb__Password: ${MONGODB_PASSWORD}
            RabbitMq__Host: rabbitmq
            RabbitMq__Port: 5672
            RabbitMq__Username: ${RABBITMQ_USERNAME}
            RabbitMq__Password: ${RABBITMQ_PASSWORD}
        depends_on:
            - mongodb

    mongodb:
        image: mongo:8.0.9
        volumes:
            - mongodb-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

    rabbitmq:
        image: rabbitmq:4.1.3-management
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    mongodb-data:
    rabbitmq-data:
