services:
    hand:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/local/hand
        ports:
            - '5260:5260'
            - '7053:7053'
        environment:
            DOTNET_ENVIRONMENT: Development
            MongoDB__Host: mongodb
            MongoDB__Port: 27017
            MongoDB__Username: ${MONGODB_USERNAME}
            MongoDB__Password: ${MONGODB_PASSWORD}
            MongoDB__Database: ${MONGODB_DATABASE}
            RabbitMQ__Host: rabbitmq
            RabbitMQ__Port: 5672
            RabbitMQ__Username: ${RABBITMQ_USERNAME}
            RabbitMQ__Password: ${RABBITMQ_PASSWORD}
        depends_on:
            - mongodb
            - rabbitmq

    mongodb:
        image: mongo:8.0.9
        volumes:
            - mongodb-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

    rabbitmq:
        image: rabbitmq:4.1.3-management
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

volumes:
    mongodb-data:
    rabbitmq-data:
