name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Install native build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev cmake

      - name: Build pokerstove library
        run: |
          cp -r ./lib/pokerstove-ext/src/programs/ps-recognize ./lib/pokerstove/src/programs/ps-recognize

          echo "add_subdirectory(ps-recognize)" >> ./lib/pokerstove/src/programs/CMakeLists.txt

          cd ./lib/pokerstove
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          cmake --build build -j 4

      - name: Upload pokerstove artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pokerstove-built
          path: ./lib/pokerstove/build

  test-unit:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run unit tests
        run: |
          dotnet test src/Domain.Test/Domain.Test.csproj

  test-integration:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download pokerstove build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pokerstove-built
          path: ./artifacts/pokerstove

      - name: Make pokerstove binaries executable
        run: |
          chmod +x ./artifacts/pokerstove/bin/*

      - name: Run integration tests
        env:
          PokerStove__Path: ${{ github.workspace }}/artifacts/pokerstove/bin/ps-recognize
        run: |
          dotnet test src/Infrastructure.Test/Infrastructure.Test.csproj
